### ISSUE TITLE
FramerateConverter with new stripemask2

### ISSUE THREAD

**Issue by kedaitinh12** [Dogway/Avisynth-Scripts#22]
I seen stripemask2 in FramerateConverter.vpy with new stripemask correction and result is better than old stripemask in framerateconverter.avsi. Can you port it to .avsi??? Thanks
https://github.com/mysteryx93/FrameRateConverter/releases/tag/v2.0-beta

**Comment by Dogway** [comment]
Thank you! will add it to the todo list, just after ExTools and QTGMC revision.

**Comment by kedaitinh12** [comment]
Thanks

**Comment by Dogway** [comment]
The port is finished except for one line:
https://github.com/mysteryx93/FrameRateConverter/blob/93985cb310d8a512b014379a033517c403a00927/FrameRateConverter.py#L407
I don't know what those 5 values do, there are no operators. I understand 'f"' relates to a function but I don't see it referenced.

**Comment by mysteryx93** [comment]
StripeMask2 is only an optimization to avoid calculating twice. I'm currently working on tweaking the parameters but that's not finished yet.

**Comment by kedaitinh12** [comment]
I think you'll be pleased with the results! It kicks v1 out of the water with beta 8
https://forum.doom9.org/showthread.php?p=1952364#post1952364

**Comment by Dogway** [comment]
Thanks mysteryx93, I was pulling my hair trying to figure out the expression. I will rebase when the script is finished. I think f"" is just Format() in AVS+.

@kedaitinh12: I will work on it when it's finished. I also want to improve it, there are several ways to detect stripes, 2D gradient magnitudes, HMT, etc. Then also will run Zopti, that's why I optimized metric functions yesterday in "SimilarityMetrics.avsi"

**Comment by Dogway** [comment]
Comitted: 401b6900513a9fb5396f272c0885812139901858

**Comment by kedaitinh12** [comment]
Thanks
