### ISSUE TITLE
Default f_taps for default flat resizer creates ringing around edges

### ISSUE THREAD

**Issue by Kogarou-san** [Dogway/Avisynth-Scripts#47]
Given an example clip with very sharp edges:

```
ColorBarsHD()
deep_resize(1920, 1080, edge="nnedi3") #nnedi3 to make sure non-ringing kernels are used in edges where possible
```
([cropped area]( https://kogarou.s-ul.eu/Q2hFFIK3.png), 400% with PointResize)
noticeable luma and chroma ringing appear around the edges. As far as I can test, it seem to be created by the flat resizer (Sinc).
When using less taps than the default (8), or a softer resizer like Hermite or Gauss, the luma ringing almost completely disappears to a single white halo in the lower cropped area, however chroma ringing still happens around the cyan-brown edge.
In comparison, running nnedi3resize(1920, 1080) has almost similar ringing in the lower cropped area, and absolutely no chroma ringing.
While this case is a bit on the extreme, I noticed deep_resize() was introducing luma and chroma ringing around lineart in anime when scaling it by 200%.

**Comment by Dogway** [comment]
Hehe, I saw that coming.
A few commits back I added the comment _"to resize natural images in high quality"_
By default deep_resize is not targeted to 2D animation or graphics because those mostly lack texture, for those you can simply use nnedi3resize(), or tune deep_resize() kernels to others with lower taps.

Indeed the ringing is not caused by the 'edge' kernel, but from 'sinc'. 'sinc' gives utmost sharpness to natural images, you can use other ones like Blackman, Lanczos or Cosine.
What I can do is to expose the chroma kernel which by default also rings a bit (Blackman8), so you can also change that. I will upload that for the next commit.

**Comment by Dogway** [comment]
Check now here: d05bd0e87d7760d79ef4ac86155bb2b9004182a8
Changed default upscale chroma kernel to Blackman6, but now you can change it with 'chroma' arg.
Also changed the 'flat' kernel to Blackman8. Sinc wasn't very good, and SincLin still leaked some ringing. You can try them out for a tiny bit more sharpness, but I think it would be better to add a sharpener afterwards in case you want more sharpness than the defaults.

**Comment by Kogarou-san** [comment]
Got it; having the chroma kernel configurable and Blackman as defaults seem nice.
I did read the comment _"to resize natural images in high quality"_ before while reading the script, but I completely forgot about it, heh
I will keep nnedi3resize in mind when resizing non-natural images

**Comment by Kogarou-san** [comment]
No, forgot to close the issue
Thank you.
